organizer/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'organizer'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('groups/join/', views.join_group, name="joinGroup"),
    path('groups/create/', views.create_group, name="create_group"),
    path('location-finder/', views.location_finder, name="location-finder"),
    path('location-finder/search', views.location_finder_query, name="location-finder/search"),
    path('groups/detail/', views.group_detail, name="groupDetail"),
    path('groups/member/reject', views.reject_group_member, name="reject_group_member"),
    path('groups/member/accept', views.accept_group_member, name="accept_group_member"),
    path('scheduler/add-event', views.add_scheduled_event, name="add_scheduled_event"),
    path('scheduler/delete-event', views.delete_event, name="delete_event"),
    path('event/', views.show_event_detail, name="show_event_detail"),
    path('event/delete-option', views.delete_event_option, name="delete_event_option"),
    path('event/finalize-option', views.finalize_event_option, name="finalize_event_option"),
    path('event/add-option', views.add_event_option, name="add_event_option"),
    path('event/stats', views.get_event_stat_row_html_fragment, name="get_event_stat_row_html_fragment"),
    path('event/change-participation', views.change_event_date_option_user_selection,
         name="change_event_date_option_user_selection"),
    path('groups/create-timeline-posting/', views.create_timeline_posting, name="createTimelinePosting"),
    path('impressum/', views.imprint, name="imprint"),
    path('datenschutz/', views.privacy, name="privacy"),
    path('account/edit', views.edit_account, name="edit_account"),
    url(r'^signup/$', views.signup, name='signup')
]

planlos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('organizer.urls')),
    # Django site authentication urls (for login, logout, password management)
    path('accounts/', include('django.contrib.auth.urls'))
]

organizer/models.py
from datetime import timezone

from django.contrib.auth.models import Group
from django.db import models
from django.utils.timezone import now

from users.models import CustomUser, Group


class TimelineEntryManager(models.Manager):
    def create_timeline_entry(self, headline: str, text: str, group: Group, author: CustomUser):
        timeline_entry = self.create(headline=headline, text=text, created_at=now(), group=group,
                                     author=author)
        return timeline_entry


class TimelineEntry(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField()
    headline = models.CharField(max_length=80)
    text = models.CharField(max_length=10000)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    objects = TimelineEntryManager()


class Event(models.Model):
    host = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=80)
    location = models.CharField(max_length=200)
    description = models.TextField(max_length=10000)
    choose_one_date_option = models.BooleanField()
    final_option_id = models.IntegerField(null=True)

    def __str__(self):
        return "Event: " + self.title + ", host: " + self.host.get_full_name() + ", location: " + self.location \
               + ", choose one date option: " + str(self.choose_one_date_option)


class EventDateOption(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return "EventDateOption for Event: " + self.event.title + ", date: " + self.date.strftime('%Y-%m-%d %H:%M')


class EventDateOptionUserSelection(models.Model):
    event_date_option = models.ForeignKey(EventDateOption, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user_selection = models.IntegerField()

    def __str__(self):
        return str(self.user_selection)

organizer/views.py
from datetime import datetime
from typing import List

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.http import require_POST, require_GET

from organizer.components import geo_component
from organizer.models import TimelineEntry
from organizer.services import event_service, timeline_service, group_and_user_service, yelp_fusion_service
from users.forms import CustomUserCreationForm, CustomUserChangeForm
from users.models import CustomUser

COMMA = ","


def index(request):
    return render(request, 'organizer/index.html')


@login_required
@require_GET
def dashboard(request):
    groups = group_and_user_service.get_confirmed_groups(request.user)
    timelines_entries = timeline_service.get_timeline_entries_for_groups(groups)
    context = {"groups": groups, "timeline_entries": timelines_entries}
    return render(request, 'organizer/dashboard.html', context)


@login_required
@require_GET
def group_detail(request):
    try:
        group: Group = group_and_user_service.get_group_by_name(request.GET.__getitem__('g'))
    except MultiValueDictKeyError:
        return redirect('/dashboard/')
    user_groups: List[Group] = group_and_user_service.get_all_groups(request.user)
    if group not in user_groups:
        return redirect('/dashboard/')
    confirmed_user_groups: List[Group] = group_and_user_service.get_confirmed_groups(request.user)
    if group not in confirmed_user_groups:
        context = {"group": group}
        return render(request, 'organizer/group_detail_not_confirmed.html', context)
    timeline_entries: List[TimelineEntry] = timeline_service.get_timeline_entries_for_group(group)
    if group_and_user_service.is_admin(request.user, group):
        unconfirmed_members = group_and_user_service.get_all_unconfirmed_members(group)
    else:
        unconfirmed_members = []
    confirmed_members = group_and_user_service.get_all_confirmed_members(group)
    events = event_service.get_events_for_group(group)
    context = {"group": group, "timeline_entries": timeline_entries, "unconfirmed_members": unconfirmed_members,
               "confirmed_members": confirmed_members, "events": events}
    return render(request, 'organizer/group_detail.html', context)


@login_required
@require_POST
def join_group(request):
    if request.method == 'POST':
        if not request.POST.__contains__('group_name'):
            return redirect('/dashboard/')
        group: Group = group_and_user_service.get_group_by_name(request.POST.__getitem__('group_name'))
        if group is None:
            messages.error(request=request,
                           message='Es existiert keine Gruppe mit dem gesuchten Namen!',
                           extra_tags='join_group')
            return redirect('/dashboard/')
        current_user: User = request.user
        group_and_user_service.join_user_to_group(current_user, group)
        return redirect('/dashboard/')


@login_required
@require_POST
def create_group(request):
    if request.method == 'POST':
        if not request.POST.__contains__('group_name'):
            return redirect('/dashboard/')
        group_name = request.POST.__getitem__('group_name')
        if group_and_user_service.group_exists(group_name):
            messages.error(request=request,
                           message='Es existiert leider bereits eine Gruppe mit dem angegebenen Gruppennamen!',
                           extra_tags='create_group')
            return redirect('/dashboard')
        current_user: User = request.user
        group_and_user_service.create_group_with_admin_user(group_name, current_user)
        return redirect('/dashboard/')


def get_group_from_get_if_user_is_member(request):
    if request.GET.__contains__('groupId'):
        group = group_and_user_service.get_group_by_id(request.GET.__getitem__('groupId'))
        if group_and_user_service.is_member(request.user, group):
            return group
    return None


@login_required
@require_GET
def location_finder(request):
    group = get_group_from_get_if_user_is_member(request)
    if not group:
        return redirect('/dashboard/')
    center = geo_component.get_groups_geographic_center(group)
    if center is not None:
        group_center = {'caption': group.name, 'center': center}
        context = {'map_center': group_center, 'group': group}
    else:
        context = {}
    return render(request, 'organizer/location-finder.html', context)


@login_required
@require_GET
def location_finder_query(request):
    group = get_group_from_get_if_user_is_member(request)
    if not group:
        return redirect('/dashboard/')
    if not request.GET.__contains__('locationQuery'):
        return redirect('/map-playground')
    if request.GET.__contains__('currentMapCenter'):
        query_string_center = request.GET.__getitem__('currentMapCenter')
        if query_string_center == '':
            current_map_center = None
        else:
            cmc_list = query_string_center.replace('LatLng(', '').replace(')', '').split(',')
            if len(cmc_list) == 2:
                current_map_center = {'lat': cmc_list[0], 'lon': cmc_list[1]}
            else:
                current_map_center = None
    else:
        current_map_center = None
    location_query = request.GET.__getitem__('locationQuery')
    if current_map_center is not None:
        map_center = {'center': current_map_center}

    else:
        group_center = geo_component.get_groups_geographic_center(group)
        if group_center is not None:
            map_center = {'caption': group.name, 'center': group_center}
        else:
            map_center = None
    if map_center is not None:
        yelp_response = yelp_fusion_service.get_businesses_by_keyword(location_query, map_center["center"]["lat"],
                                                                      map_center["center"]["lon"], 40)
        context = {'yelp': yelp_response, 'map_center': map_center, 'group': group}
    else:
        context = {}
    return render(request, 'organizer/location-finder.html', context)


@login_required
@require_POST
def create_timeline_posting(request):
    group: Group = group_and_user_service.get_group_by_name(request.POST.__getitem__('group'))
    author: CustomUser = request.user
    text: str = request.POST.__getitem__('text')
    headline: str = request.POST.__getitem__('headline')
    if group and text != '' and headline != '':
        timeline_service.add_timeline_entry_to_group(headline, text, group, author)
        return redirect('/groups/detail?g=' + group.name)
    else:
        return dashboard(request)


@login_required
@require_POST
def accept_group_member(request):
    group: Group = group_and_user_service.get_group_by_name(request.POST.__getitem__('group_name'))
    members: List[CustomUser] = extract_members(request.POST.__getitem__('member_ids'))
    for member in members:
        group_and_user_service.accept_user(member, group)
    return HttpResponse(status=200);


@login_required
@require_POST
def reject_group_member(request):
    group: Group = group_and_user_service.get_group_by_name(request.POST.__getitem__('group_name'))
    members: List[CustomUser] = extract_members(request.POST.__getitem__('member_ids'))
    for member in members:
        group_and_user_service.reject_user(member, group)
    return HttpResponse(status=200)


@login_required
@require_POST
def add_scheduled_event(request):
    event_name = request.POST.__getitem__('eventName')
    event_location = request.POST.__getitem__('eventLocation')
    event_description = request.POST.__getitem__('eventDescription')
    event_choose_one_date = request.POST.__getitem__('choose_one_date') == "findDate"
    event_group_id = request.POST.__getitem__('groupId')
    event_group = Group.objects.get(id=event_group_id)
    event_dates = request.POST.getlist('date')
    event_times = request.POST.getlist('time')
    # should be avoided from frontend
    if len(event_times) != len(event_dates):
        return redirect('/dashboard/')
    event_date_times = []
    for i in range(len(event_dates)):
        event_date_times.append(event_dates[i] + ' ' + event_times[i])
    event_id = event_service.create_event_with_options(request.user, event_group, event_name, event_location,
                                                       event_description, event_choose_one_date, event_date_times)
    return redirect('/event?eventId=' + str(event_id))


@login_required
@require_POST
def delete_event(request):
    if not request.POST.__contains__('eventId'):
        return redirect('/dashboard')
    event_id = request.POST.__getitem__('eventId')
    event = event_service.get_event_by_id(event_id)
    if event is None:
        return redirect('/dashboard')
    redirect_url = '/groups/detail?g=' + event.group.name + '&tab=schedule'
    if not event.host == request.user:
        messages.error(request, "Der Termin konnte nicht gelöscht werden!")
    else:
        event_service.delete_event(event)
        messages.success(request, "Der Termin wurde erfolgreich gelöscht!")
    return redirect(redirect_url)


@login_required
def show_event_detail(request):
    if not request.GET.__contains__('eventId'):
        return redirect('/dashboard/')
    event_id = request.GET.__getitem__('eventId')
    event = event_service.get_event_by_id(event_id)
    users_groups = group_and_user_service.get_all_groups(request.user)
    if event.group not in users_groups:
        return redirect('/dashboard/')
    members = group_and_user_service.get_all_confirmed_members(event.group)

organizer/templates/organizer/add-event.html
<form action="/scheduler/add-event" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="eventName">Name des Termins</label>
        <input class="form-control" type="text" id="eventName" name="eventName">
    </div>
    <div class="form-group">
        <label for="eventLocation">Ort des Termins</label>
        <input class="form-control" type="text" id="eventLocation" name="eventLocation">
        <a href="{% url 'organizer:location-finder' %}?groupId={{ groupId }}" class="btn btn-info form-control">Jetzt einen Ort suchen!</a>
    </div>
    <div class="form-group">
        <label for="eventDescription">Beschreibung des Termins</label>
        <textarea class="form-control" id="eventDescription" name="eventDescription"></textarea>
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="choose_one_date" id="findDate" value="findDate"
                   checked>
            <label class="form-check-label" for="inlineRadio1">Einen Termin finden</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="choose_one_date" id="multipleDates"
                   value="multipleDates">
            <label class="form-check-label" for="inlineRadio2">Terminserie erstellen</label>
        </div>
    </div>
    <label for="dateTimes">Wann kann der Termin stattfinden?</label>
    <div id="dateTimes">
        {% include 'organizer/event-option-form.html' %}
    </div>

    <div class="form-group">
        <button type="button" class="btn btn-success plus-button" id="addEventDateTime">Option hinzufügen</button>
        <button type="button" class="btn btn-danger minus-button" id="removeEventDateTime">Option entfernen</button>
    </div>
    <input type="hidden" name="groupId" value="{{ group.id }}">
    <button type="submit" class="btn btn-primary">Losplanen</button>
</form>

organizer/templates/organizer/create_timeline_entry.html
<div class="createTimelineEntry row">
    <div class="col">
        <p>
            <button class="btn btn-secondary" type="button" data-toggle="collapse"
                    data-target="#collapseCreateTimelineEntry" aria-expanded="false"
                    aria-controls="collapseCreateTimelineEntry">
                Beitrag verfassen &#9997;
            </button>
        </p>
        <div class="collapse" id="collapseCreateTimelineEntry">
            <div class="card card-body">
                <form method="post" class="createTimelineEntry" action="/groups/create-timeline-posting/">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="createTimelineEntryFormHeadline">Titel</label>
                        <input type="text" class="form-control" name="headline" id="createTimelineEntryFormHeadline"
                               placeholder="Titel" required>
                    </div>
                    <div class="form-group">
                        <label for="createTimelineEntryFormText">Text</label>
                        <textarea class="form-control" id="createTimelineEntryFormText" name="text" rows="5" required></textarea>
                    </div>
                    <input type="hidden" id="createTimelineEntryFormGroup" name="group" value="{{ group }}">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Los!</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

organizer/templates/organizer/dashboard.html
{% extends "organizer/base_generic.html" %}

{% block styles %}
    <link rel="stylesheet" href="/static/css/dashboard.css">
{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    {% if groups|length > 0 %}
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-3">
                <h3>Deine Gruppen</h3>
                <ul class="list-group mb-4">
                    {% for group in groups %}
                        <li class="list-group-item"><a href="/groups/detail?g={{ group.name }}">{{ group.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <div id="accordion">
                    <div class="card">
                        <div class="card-header" id="heading-joinGroup">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-joinGroup"
                                        aria-expanded="true" aria-controls="collapse-joinGroup">
                                    Einer Gruppe beitreten
                                </button>
                            </h5>
                        </div>

                        <div id="collapse-joinGroup" class="collapse" aria-labelledby="heading-joinGroup"
                             data-parent="#accordion">
                            <div class="card-body">
                                  {% include "organizer/join_group.html" %}
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="heading-createGroup">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-createGroup"
                                        aria-expanded="true" aria-controls="collapse-createGroup">
                                    Eine Gruppe erstellen
                                </button>
                            </h5>
                        </div>

                        <div id="collapse-createGroup" class="collapse" aria-labelledby="heading-createGroup"
                             data-parent="#accordion">
                            <div class="card-body">
                                  {% include "organizer/create_group.html" %}
                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <div class="col">
                <h3>Neuigkeiten</h3>
                {% with with_group_name=1 %}
                    {% include "organizer/timeline.html" %}
                {% endwith %}
            </div>
        </div>
    {% else %}
        <div class="row mb-4">
            <div class="col text-center">
                Du bist zur Zeit noch kein Mitglied in einer Gruppe! Trete jetzt einer Gruppe bei und plane los!
                Oder gründe noch heute Deine eigene Gruppe!
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h3>Einer Gruppe beitreten</h3>
                {% include  "organizer/join_group.html" %}
            </div>
            <div class="col">
                <h3>Eine Gruppe erstellen</h3>
                {% include "organizer/create_group.html" %}
            </div>
        </div>
    {% endif %}
{% endblock %}

organizer/templates/organizer/edit_account.html
{% extends "organizer/base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include 'organizer/messages.html' with messages=messages %}
    <h2>Deinen Account bearbeiten</h2>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="col-md">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="col-md">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                {{ form.street|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                {{ form.zip_code|as_crispy_field }}
            </div>
            <div class="col-md">
                {{ form.city|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                {{ form.country|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                {{ form.phone|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Speichern</button>
    </form>

{% endblock %}

organizer/templates/organizer/event.html
{% extends "organizer/base_generic.html" %}

{% load custom_tags %}

{% block styles %}
    <link rel="stylesheet" href="/static/css/event.css">
{% endblock %}

{% block scripts %}
    <script src="/static/js/event.js" type="module"></script>
{% endblock %}

{% block content %}
    {% include 'organizer/messages.html' %}
    <h2>{{ event.title }} von {{ event.host.first_name }} {{ event.host.last_name }} ({{ event.group.name }})</h2>
    <h3>Ort: {{ event.location }}</h3>
    <p class="text-center">{{ event.description }}</p>
    {% if final_option %}
        <p class="text-center my-4">Diese Terminumfrage ist abgeschlossen. Der Gastgeber hat eine finale Option
            gewählt!</p>
    {% endif %}
    {% csrf_token %}
    <span class="event-id">{{ event.id }}</span>
    <div class="table-responsive">
        <table class="table table-bordered event-table">
            <thead>
            <tr>
                <th scope="col">Name</th>
                {% for edo in event_date_options %}
                    <th scope="col">
                        {% if final_option and final_option.id == edo.id %}
                            <div>✔️ <b>Finale Option</b></div>
                        {% endif %}
                        <div>{{ edo.date }}</div>
                        {% if event.host == request.user %}
                            <form method="post" action="/event/delete-option" class="mt-2">
                                {% csrf_token %}
                                <input type="hidden" name="optionId" value="{{ edo.id }}">
                                <input type="submit" class="btn btn-danger btn-sm" value="Option löschen">
                            </form>
                            {% if event.choose_one_date_option %}
                                <form method="post" action="/event/finalize-option" class="mt-2">
                                    {% csrf_token %}
                                    <input type="hidden" name="optionId" value="{{ edo.id }}">
                                    <input type="submit" class="btn btn-success btn-sm" value="Als final wählen">
                                </form>
                            {% endif %}
                        {% endif %}
                    </th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for member in members %}
                <tr {% if user == member %}id="tr-current-user" class="table-info"{% endif %}>
                    <td>{{ member.first_name }} {{ member.last_name }}</td>
                    {% for edo in event_date_options %}
                        <td class="event-selection-tablecell disable-selection">
                            <span class="event-date-option-id">{{ edo.id }}</span>
                            <span class="event-selection-icon event-selection-no {% if selections|get_item:edo.id|get_item:member.id|edous_get_selection == "NO" %}evt-selected {% endif %}"
                                  data-selection="NO">❌</span>
                            <span class="event-selection-icon event-selection-maybe {% if selections|get_item:edo.id|get_item:member.id|edous_get_selection == "MAYBE" %}evt-selected{% endif %}"
                                  data-selection="MAYBE">❓</span>
                            <span class="event-selection-icon event-selection-yes {% if selections|get_item:edo.id|get_item:member.id|edous_get_selection == "YES" %}evt-selected{% endif %}"
                                  data-selection="YES">✅</span>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            <tr id="event-stat-row"></tr>
            </tbody>
        </table>
    </div>



    {% if event.host == request.user %}
        <button class="btn btn-primary mb-3 mt-4" type="button" data-toggle="collapse" data-target="#collapseAddOption"
                aria-expanded="false" aria-controls="collapseAddOption">
            Terminoption hinzufügen
        </button>

        <div class="collapse" id="collapseAddOption">
            <div class="card card-body">
                <form method="post" action="/event/add-option">
                    {% csrf_token %}
                    {% include 'organizer/event-option-form.html' %}
                    <input type="hidden" name="eventId" value="{{ event.id }}">
                    <input type="submit" class="btn btn-success float-right" value="Option hinzufügen">
                </form>
            </div>
        </div>
    {% endif %}

{% endblock %}

organizer/templates/organizer/event_stat_row.html
{% load custom_tags %}

<td>Gesamt</td>
{% for edo in event_date_options %}
    <td>
        <div>{{ stat_map|get_item:edo.id|get_item:"YES" }} ✅</div>
        <div>{{ stat_map|get_item:edo.id|get_item:"MAYBE" }} ❓</div>
        <div>{{ stat_map|get_item:edo.id|get_item:"NO" }} ❌</div>
    </td>
{% endfor %}

organizer/templates/organizer/footer.html
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-text" id="footer-claim">plan-los.org</a>
    <a class="navbar-text footer-link" href="{% url 'organizer:imprint' %}">Impressum</a>
    <a class="navbar-text footer-link" href="{% url 'organizer:privacy' %}">Datenschutzerklärung</a>
    <a class="navbar-text footer-link" href="mailto:info@plan-los.org">Kontakt</a>
</nav>

organizer/templates/organizer/group_detail_not_confirmed.html
{% extends "organizer/base_generic.html" %}

{% block styles %}
    <link rel="stylesheet" href="/static/css/group_detail.css">
{% endblock %}

{% block content %}
    <h1>{{ group.name }}</h1>
    <div class="row not-confirmed">
            Leider wurde Deine Zugehörigkeit zu dieser Gruppe noch von keinem Gruppenadministrator bestätigt!
    </div>

{% endblock %}

organizer/templates/organizer/imprint.html
{% extends "organizer/base_generic.html" %}


{% block content %}
<h1>Impressum</h1>

<h2>Angaben gem&auml;&szlig; &sect; 5 TMG</h2>
<p>Lukas Thiell<br />
Eimsb&uuml;tteler Stra&szlig;e 105<br />
22769 Hamburg</p>

<h2>Kontakt</h2>
<p>E-Mail: info@plan-los.org</p>

<p>Quelle: <a href="https://www.e-recht24.de">https://www.e-recht24.de</a></p>
{% endblock %}

organizer/templates/organizer/map_popup_content.html
<div class="map-popup-name">
    <a href='{{ bu.url }}' target='_blank'>{{ bu.name }}</a>
</div>
<div>
    <a href="{% url 'organizer:groupDetail' %}?g={{ group_name }}&tab=schedule&eventLocation={{ bu.name }}, {% for dap in bu.location.display_address %}{{ dap }}{% if forloop.counter < bu.location.display_address|length %}, {% endif %}{% endfor %}"
       class="btn btn-outline-dark btn-sm">Termin an diesem Ort erstellen</a>
</div>
<div>
    {% for category in bu.categories %}
        {{ category.title }}{% if forloop.counter < bu.categories|length %},{% endif %}
    {% endfor %}
</div>
<div>
    Bewertung: {{ bu.rating }}/5
</div>
<div class="map-popup-address">
    {% for dap in bu.location.display_address %}
        {{ dap }}{% if forloop.counter < bu.location.display_address|length %},{% endif %}
    {% endfor %}
</div>
<a href='{{ bu.url }}' target='_blank'>
    <img src='{{ bu.image_url }}' alt='{{ bu.name }}'>
</a>

organizer/templates/organizer/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success">
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger">
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

organizer/templates/organizer/timeline.html
{% if timeline_entries|length == 0 %}
    <p class="text-center">Hier wurden noch keine Beiträge veröffentlicht. Schreibe doch einfach selbst den ersten!</p>
{% endif %}
{% for tle in timeline_entries %}
    {% include "organizer/timeline_entry.html" %}
{% endfor %}